{
 "title": "Chainlink Node Monitoring Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Current Head",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "head_tracker_current_head{job=~\"Chainlink_Node_1.*\"}"
    }
   ]
  },
  {
   "title": "Log Error Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "log_error_count{job=~\"Chainlink_Node_1.*\"}"
    }
   ]
  },
  {
   "title": "Log Critical Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "log_critical_count{job=~\"Chainlink_Node_1.*\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Eth Balance",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "eth_balance{job=~\"Chainlink_Node_1.*\"}",
     "legendFormat": "{{account}}"
    }
   ]
  },
  {
   "title": "Chainlink UI Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "up{job=~\"Chainlink_Node_1.*\"}"
    }
   ]
  },
  {
   "title": "Queue Size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "pipeline_runs_queued{job=~\"Chainlink_Node_1.*\"}"
    }
   ]
  },
  {
   "title": "New heads per minute",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(head_tracker_heads_received{job=~\"Chainlink_Node_1.*\"}[1m])*60"
    }
   ]
  },
  {
   "title": "Successful Transactions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "tx_manager_num_successful_transactions{job=~\"Chainlink_Node_1.*\"}"
    }
   ]
  },
  {
   "title": "Eth Balance",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "eth_balance{job=~\"Chainlink_Node_1.*\"}"
    }
   ]
  },
  {
   "title": "Gas Price Percentiles",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gas_updater_set_gas_price{job=~\"Chainlink_Node_1.*\",block_num=\"\"}/1000000000",
     "legendFormat": "actual"
    }
   ]
  },
  {
   "title": "Gas Price Percentiles",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gas_updater_all_gas_price_percentiles{percentile!=\"100%\",job=~\"Chainlink_Node_1.*\"}/1000000000",
     "legendFormat": "{{percentile}}"
    }
   ]
  },
  {
   "title": "Node CPU Load",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 15, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(process_cpu_seconds_total{ job=~\"Chainlink_Node_1.*\"}[1d])",
     "legendFormat": "{{task_type}}"
    }
   ]
  },
  {
   "title": "New heads per minute",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(head_tracker_heads_received{job=~\"Chainlink_Node_1.*\"}[1m])*60"
    }
   ]
  },
  {
   "title": "Number of Gas Bumps",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "gas_updater_set_gas_price{job=~\"Chainlink_Node_1.*\"}/1000000000",
     "legendFormat": "Set Gas Price"
    },
    {
     "expr": "gas_updater_set_tip_cap{job=~\"Chainlink_Node_1.*\"}/1000000000",
     "legendFormat": "Set Tip Cap"
    }
   ]
  },
  {
   "title": "Current Head increase",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(head_tracker_current_head{job=~\"Chainlink_Node_1.*\"}[1m])*60",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Number of Jobs",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 9 },
   "targets": [
    {
     "expr": "increase(pipeline_runs_queued{job=~\"Chainlink_Node_1.*\"}[1h])\n"
    }
   ]
  },
  {
   "title": "RPC Polling Attemps Succeeded",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 15, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(pool_rpc_node_polls_success{job=~\"Chainlink_Node_1.*\"}[3h]) ",
     "legendFormat": "{{task_type}}"
    }
   ]
  },
  {
   "title": "Head Tracker Heads in Queue",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 9 },
   "targets": [
    {
     "expr": "head_tracker_current_head{job=~\"Chainlink_Node_1.*\"}",
     "legendFormat": "head_tracker_current_head"
    },
    {
     "expr": "head_tracker_heads_received{job=~\"Chainlink_Node_1.*\"}",
     "legendFormat": "head_tracker_heads_received"
    }
   ]
  },
  {
   "title": "Node UI Componets Health",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "health{instance=\"localhost:6688\"}",
     "legendFormat": "{{service_id}}"
    }
   ]
  },
  {
   "title": "Transaction pool",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 10, "y": 15 },
   "targets": [
    {
     "expr": "tx_manager_num_finalized_transactions{job=~\"Chainlink_Node_1*\"}",
     "legendFormat": "executable {{job}}"
    }
   ]
  },
  {
   "title": "All Job Runs",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 15 },
   "targets": [
    {
     "expr": "increase(pipeline_runs_queued{job=~\"Chainlink_Node_1.*\"}[1d])\n",
     "legendFormat": "{{job_spec_id}}"
    }
   ]
  }
 ]
}